### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Ellon-M** [ohyajk/portfolio1#13]
When the menu is open, and the screen is resized to desktop size, two menus are appearing. It would nice to hide one.

https://github.com/ohyajk/portfolio1/blob/b9e9aefb9cee88efe6167c7e6ee6bd340347b995/index.html#L22-L25

**Comment by ohyajk** [comment]
Thanks for your time. I will definitely consider this and try to fix this problem as soon as possible.
