### ISSUE TITLE
About font-family

### ISSUE THREAD

**Issue by asifaminisonline** [ohyajk/portfolio1#6]
Hi, JK while checking your code everything is almost incredible but I would like to recommend some changes for best practices.👍 😃 😃

1. It's nice to import the font family you want to use in your project, use it universally at the top of your CSS file because you can save a lot of time and increase your productivity.
2. Please try to give meaningful class names for the tags.

Cheers and Happy coding!👏👏👏

**Comment by ohyajk** [comment]
Can you elaborate on how I can save time using the font family @import at the top?
